# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'nfs', nfs_udp: false

  # libvirt.
  config.vm.define "libvirt" do |libvirt|
    libvirt.vm.hostname = "libvirt-ubuntu2004"
    libvirt.vm.box = "file://builds/libvirt-ubuntu2004.box"

    config.vm.provider :libvirt do |v|
      v.driver = "kvm"
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.provision "shell", inline: "echo Hello, World"
  end

end
